config/urls.py
# control + shift + p
## python interpretor => django가상환경 선택.
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('account/', include('account.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name="home"), # http:/127.0.0.1:8000/   
]

#### 파일업로드 관련 설정. MEDIA_ROOT의 url로 요청이 들을 받을 수 있도록 설정.
# #(개발서버-runserver 에서 필요)
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# http://ip:8000   /polls/list

# TemplateView
##  요청을 받으면 단순히 template을 응답하는 View를 만들 경우 사용.
##   - template 파일의 경로만 지정.
# def home(request):
#     return render(request, "home.html")

polls/urls.py
from django.urls import path
from . import views   # polls/views.py 모듈 import
app_name = "polls"

# 요청 url - 실행할 view 
## path("url", view함수, name="이 설정이름")
urlpatterns = [
    path("welcome", views.welcome, name="welcome"),
    path("vote_list", views.list, name="list"),
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path('vote_create', views.vote_create, name="vote_create"),
    path('', views.list, name="polls_home"),  # http://127.0.0.1:8000/polls/
]
# http://127.0.0.1:8000/polls/list

# http://127.0.0.1:8000/polls/vote_form/3
# path parameter 변수 설정. <타입:변수이름>
## 타입: 문자열로 넘어온 값을 어떤 타입으로 변환할 지 지정.
## 변수이름: view의 어떤 파라미터에 값을 넘길지 view함수 파라미터이름

polls/models.py
# polls/models.py

from django.db import models

# 모델클래스
# 1. django.db.models.Model 상속
# 2. class 변수로 테이블의 컬럼과 연결된 변수(Model Field)를 선언.
#     - 변수명(컬럼명) = ModelField(type, 컬럼 제약조건 등)를 대입

# 질문(Question) 모델 - DB의 QUESTION 테이블과 연결.
class Question(models.Model):
    # 클래스 변수
    #   변수명: 컬럼명,
    #   Model Field 객체 - 컬럼 타입, 제약조건 설정.
    # primary key Field를 지정하지 않으면 id: 정수 자동증가 컬럼을 primary key 컬럼으로 생성
    question_text = models.CharField(max_length=200) # 문자열 타입. varchar(200)
    pub_date = models.DateTimeField(auto_now_add=True)   # 날짜/시간 타입
    # auto_add_now=True -> insert할 때 날짜/시간을 입력.
    
    def __str__(self):
        return f"{self.id}. {self.question_text}"


#  보기(Choice) 모델 - DB의 CHOICE 테이블과 연결

class Choice(models.Model):

    choice_text = models.CharField(max_length=200) # 보기문장
    votes = models.IntegerField(default=0) # 몇명이 선택했지 저장. 정수형.
    # Foreign key - QUESTION.id(PK) 참조
    question =  models.ForeignKey(
        Question, # 참조할 model클래스
        on_delete=models.CASCADE,  # 부모테이블의 참조값이 삭제된 경우 어떻게 할지.\
        # related_name="my_choice_set"        
    )
    
    def __str__(self):
        return f"{self.id}. {self.choice_text}"

polls/views.py
# polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse # url path설정의 name을 가지고 url을 만들어주는 함수.
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from datetime import datetime
from polls.models import Question, Choice

# welcome page
# View 함수 -> 1개 이상 파라미터선언(HttpRequest객체를 받는 파라미터)
def welcome_old(request):
    print("Welcome 실행")
    # 응답: string
    now = datetime.now().strftime("%Y년 %m월 %d일 %H시 %M분 %S초")
    res_html = f"""
        <html>
            <head><title>Welcome</title></head>
            <body>
                <h1>환영합니다.</h1>
                <h2>현재시간: {now}</h2>
            </body>
        </html>
    """
    return HttpResponse(res_html)

# template 저장할 디렉토리를 생성 - app/templates
## polls/templates/polls
def welcome(request):
    now = datetime.now().strftime("%Y년 %m월 %d일 %H시 %M분 %S초")
    # welcome.html 템플릿을 실행한 결과 html을 받아오기.
    res = render(
        request,  # HttpRequest (Http 요청정보를 담은 객체)
        "polls/welcome.html", # 호출할 template파일경로.
        {"current":now, "name":"홍길동"} 
        # context value: view가 template에 전달하는 값들.
    ) #welcome.html의 결과를 가지고 있는 HttpResponse를 반환.  
    print("res type:", type(res))
    return res


# 설문 목록을 응답하는 View
## 전체 Question을 조회해서 목록 html을 반환.
## url:  polls/list
## view함수: list
## template: polls/list.html   # polls/templates/[polls/list.html]
def list_old(request):
    # DB에서 question들을 조회
    question_list = Question.objects.all().order_by("-pub_date")
    # 질문 목록 template을 호출.
    return render(
        request,
        "polls/list.html",
        {"question_list":question_list}
    )

def list(request):
    """
    Paging 처리 view
    - 요청파라미터로 page번호를 받는다.
    - context data (Template에게 전달하는 값)
        - 현재 페이지의 데이터
        - 현재 페이지가 속한 페이지 그룹의 시작페이지번호, 끝페이지 번호
        - 현재 페이지 그룹의 시작페이지가 이전페이지가 있는지 여부/이전페이지 번호
        - 현재 페이지 그룹의 끝페이지가 다음페이지가 있는지 여부/다음페이지 번호
    """
    paginate_by = 10  # 한 페이지 당 데이터 개수
    page_group_count = 10 # 페이지그룹 당 페이지수 (한번에 몇개 페이지씩 보여줄지)
    # http://127.0.0.1:8000/polls/list?page=3
    current_page = int(request.GET.get("page", 1))

    # Paginator 생성.
    question_list = Question.objects.all().order_by("-pk")
    pn = Paginator(question_list, paginate_by)

    # 현재 페이지가 속한 페이지그룹의 시작/끝 페이지 번호 조회
    start_index = int((current_page - 1) / page_group_count) * page_group_count
    end_index = start_index + page_group_count

    page_range = pn.page_range[start_index : end_index]

    # context_data: dict -> template 호출할 때 전달.
    context_data = {
        "page_range":page_range,
        "question_list": pn.page(current_page)
    }

    # 그룹의 시작페이지의 이전페이지 유무/있다면 페이지번호
    # 그룹의 끝페이지의 다음페이지 유무/있다면 페이지번호
    ### 시작 페이지
    start_page = pn.page(page_range[0])
    end_page = pn.page(page_range[-1])
    has_previous = start_page.has_previous()
    has_next = end_page.has_next()

    if has_previous: # 시작페이지의 이전페이지가 있다면
        context_data['has_previous'] = has_previous
        context_data['previous_page_number'] = start_page.previous_page_number

    if has_next: # 끝페이지가 다음페이지를 가지고 있다면
        context_data['has_next'] = has_next
        context_data['next_page_number'] = end_page.next_page_number

    return render(
        request, "polls/list.html", context_data
    )


# 설문폼 페이지로 이동하는 View
## 설문 문항(문제)의 id(pk)를 받아서 설문폼을 응답.
## 문제 ID를 path parameter로 입력받는다.
##    http://url:port/vote_form?pk=3 => 요청파라미터(QueryString)
##    http://url:port/polls/vote_form/문제번호 => 패스 파라미터
# 요청URL: /polls/voteform
# view: vote_form
# 응답 template: polls/vote_form.html
def vote_form(request, question_id):
    # question_id: path parameter로 문제 id값을 받을 변수
    #  -> urls.py에 path 설정시 지정.

    # 1. question_id로 Question 조회
    question = Question.objects.get(pk=question_id)

    # 2. 조회결과로 응답 페이지를 생성
    return render(
        request, "polls/vote_form.html", {"question":question}
    )
    # print("없는 문제를 조회했습니다. -> error 응답페이지로 이동.")


# 투표 처리
## 요청URL: /polls/vote
## view : vote
## 응답: - 정상 처리: vote_result view를 호출 (redirect방식)
##       - 요청파라미터 검증 실패(선택안하고 투표) -> polls/vote_form.html 

# View 에서 요청파라미터 조회
## GET 요청: request.GET['요청파라미터이름'], request.GET.get("요청파라미터이름")
## POST 요청: request.POST['요청파라미터이름'], request.POST.get("요청파라미터이름")
# []: 요청파라미터이름으로 넘어온게 없으면 Exception 발생
# get: 요청파라미터이름으로 넘어온게 없으면 None 반환.

def vote(request):
    # post 요청파라미터 - name: choice
    choice_id = request.POST.get("choice")
    question_id = request.POST.get("question_id")

    if choice_id is not None:
        # 보기의 votes를 1 증가하도록 update
        choice = Choice.objects.get(pk=choice_id)
        choice.votes += 1
        choice.save()

        # q = Question.objects.get(pk=question_id)
        # return render(
        #     request, "polls/vote_result.html", {"question":q}
        # )

        # 투표결과 페이지로 이동 -> view를 호출
        # url = f"/polls/vote_result/{question_id}" # view의 url
        url = reverse("polls:vote_result", args=[question_id])
        print(url)
        return redirect(url)
        # redirect(url): Redirect 방식 응답. 
        # Web Browser가 지정한 url로  다시 요청하도록 응답. 

    else: # choice요청파라미터가 없는 경우.
        question = Question.objects.get(pk=question_id)
        return render(
            request, 
            "polls/vote_form.html",
            {"question":question, "error_msg":"보기를 선택하세요."}
            
        )


# 투표결과를 응답하는 View
# 요청 url: poll/vote_result/question_id
# view : vote_result
# 응답: polls/vote_result.html

def vote_result(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'polls/vote_result.html', {"question":question})


# 설문 등록 처리 View
# 요청 url: /polls/vote_create
# view: vote_create
##     - GET요청: 문제-보기 등록 폼 페이지를 응답
##     - POST요청: 등록 처리.
# 응답 - GET: polls/vote_create.html
#        POST: list view 를 호출 => redirect() 이동(새로고침 해도 추가 되지 않게.)
## HTTP 요청방식을 조회 - request.method: "POST", "GET"
@login_required
def vote_create(request):
    http_method = request.method
    if http_method == "GET": # 등록폼을 반환
        return render(request, "polls/vote_create.html")

    elif http_method == "POST":# 등록처리
        #1. 요청파라미터(제목, 보기) 읽기.
        question_text = request.POST.get('question_text')
        # 같은이름으로 여러개 값이 넘어온 경우(choice_text=aaa&choice_text=bbb&)
        ## request.GET/POST.getlist('요청파라미터이름'): list
        choice_list = request.POST.getlist("choice_text")

        #2. DB에 저장(insert)
        q = Question(question_text=question_text)
        q.save() # 문제 저장
        for choice_text in choice_list: # 보기들 저장
            choice = Choice(choice_text=choice_text, question=q)
            choice.save()
        
        # 응답 페이지로 이동 - 목록페이지(list)
        # url = "/polls/list"
        # return redirect(url)
        return redirect(reverse("polls:list"))

polls/templates/polls/list.html
<!-- templates/polls/list.html -->
{% extends "layout.html" %}

{% block title %}설문목록{% endblock %}
{# layerout.html 의 title 블록에 설문 목록을 넣어라. #}

{% block contents %}
    <h1>설문 목록</h1>
    <div class="list-group"> 
    {% for question in question_list %}
        <a  href="{% url 'polls:vote_form' question.pk %}" 
            class="list-group-item list-group-item-action">
            {{question.pk}}. {{question.question_text|truncatewords:4}}
            - {{question.pub_date | date:'Y/m/d H:i:s'}}
        </a>
    {% empty %}
        <b>아직 등록된 설문이 없습니다.</b>
    {% endfor%}
    </div>
    <!-- 페이징 처리 - 페이지 링크 -->
    <ul class="pagination mt-3">
        {# 이전페이지 그룹으로 이동 버튼 #}
        {% if has_previous %}
            <li class="page-item">
                <a  href="{% url 'polls:list' %}?page={{previous_page_number}}" 
                    class="page-link">
                    이전
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class='page-link'>이전</span>
            </li>
        {% endif %}

        {# 페이지 번호 링크 - 현재페이지에는 링크를 걸지 않는다. page.number #}
        {% for page_no in page_range %}
            {% if question_list.number == page_no %}
                <li class="page-item active">
                    <span class="page-link">{{page_no}}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a href="{% url 'polls:list' %}?page={{page_no}}" class="page-link">
                        {{page_no}}
                    </a>
                </li>
            {% endif %}
        {% endfor %}


        {# 다음페이지 그룹으로 이동 버튼 #}
        {% if has_next %}
            <li class="page-item">
                <a href="{% url 'polls:list' %}?page={{next_page_number}}" class="page-link">
                    다음
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class='page-link'>다음</span>
            </li>
        {% endif %}



    </ul>
{% endblock %}

polls/templates/polls/vote_create.html
<!-- polls/templates/polls/vote_create.html -->
{% extends "layout.html" %}
{% block title%}설문 문제 등록{%endblock%}
{% block contents%}
<h1>설문 문제 등록</h1>
<!-- action생략: 현재 url로 요청. -->
<form method="post">
    {% csrf_token %}
    <h2>질문</h2>
    <input type="text" name="question_text" required class="form-control">
    <h2>보기</h2>
    <div id="choice_layer">
        <input type="text" name="choice_text" required class="form-control">
    </div>
    <div class="mt-3">
        <button type="button" onclick="addChoice()" class="btn btn-primary">보기 추가</button>
        <button type="button" onclick="delChoice()" class="btn btn-danger">보기 제거</button>
        <button type="submit" class="btn btn-primary">문제 등록</button>
    </div>
</form>
<script>
    function addChoice() {
        // div#choice_layer 에 보기 입력 text field 추가.
        input = document.createElement("input"); // <input>
        //property(attribute)를 추가
        input.setAttribute("type", "text");   // <input type='text'>
        input.setAttribute("name", "choice_text"); // <input type='text' name='choice'>
        input.setAttribute('required', true); // <input ... required>
        input.setAttribute("class", "form-control");

        layer = document.getElementById('choice_layer');
        layer.append(input);
    }
    function delChoice() {
        // div#choice_layer 의 보기 입력 text field를 한개 제거. 
        // 하나만 있을 경우는 제거하지 안한다.
        // 노드: 부모노드.removeChild(삭제할 노드)
        layer = document.getElementById('choice_layer');
        //두개 이상일 때만 삭제
        if (layer.children.length >= 2) {
            layer.removeChild(layer.lastChild)
        } else {
            alert("보기가 한개이면 삭제할 수없습니다.");
        }
    }

</script>
{% endblock %}

polls/templates/polls/vote_form.html
<!-- templates/polls/vote_form.html -->

<!-- templates/polls/vote_result.html -->
{% extends "layout.html" %}
{% block title %}설문폼{% endblock %}
{% block contents%}
<h1>설문폼</h1>
<!-- 만약에 error_msg가 context data로 넘어온게 있다면 출력 -->
{% if error_msg != None %}
    <div style="color:red;font-size:0.8em">
        {{error_msg}}
    </div>
{% endif %}


<h2>{{question.pk}}. {{question.question_text}}</h2>
<form action="{% url 'polls:vote' %}" method="POST" class="mt-3">
    {% csrf_token %}
    <!--View에서 검증 실패시 Question을 다시 조회하기 위해서 넘겨주는 값. 
        화면에 보일 필요 없으므로 hidden type으로 설정 -->
    <input type="hidden" name="question_id" value="{{question.pk}}">
    {% for choice in question.choice_set.all %}
        <input type="radio" class='form-check-input' name="choice" value="{{choice.pk}}" id="{{choice.pk}}">
        <label for="{{choice.pk}}">{{choice.choice_text}}</label><br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary btn-sm">투표</button>
        <button type="reset" class="btn btn-primary btn-sm">선택해제</button>
    </div>
</form>
{% endblock %}

polls/templates/polls/vote_result.html
<!-- templates/polls/vote_result.html -->
{% extends "layout.html" %}
{% block title %}설문 결과{% endblock %}
{% block contents%}
<h1>설문 결과</h1>
<h2>{{question.pk}}. {{question.question_text}}</h2>
<ol>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} - {{choice.votes}}</li>
    {% endfor %}
</ol>
{% endblock %}

polls/templates/polls/welcome.html
<!-- polls/templates/polls/welcome.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Page</title>
</head>
<body>
    <h1>환영합니다. {{name}}</h1>
    <h2>현재시간: {{current}}</h2> 
</body>
</html>