account/urls.py
# account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("create", views.create, name="create"),
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("detail", views.user_detail, name="detail"),
    path('password_change', views.password_change, name='password_change'),
    path('update', views.user_update, name='update'),
    path('delete', views.user_delete, name="delete"),
]

config/urls.py
# control + shift + p
## python interpretor => django가상환경 선택.
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('account/', include('account.urls')),
    path('', TemplateView.as_view(template_name="home.html"), name="home"), # http:/127.0.0.1:8000/   
]

#### 파일업로드 관련 설정. MEDIA_ROOT의 url로 요청이 들을 받을 수 있도록 설정.
# #(개발서버-runserver 에서 필요)
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# http://ip:8000   /polls/list

# TemplateView
##  요청을 받으면 단순히 template을 응답하는 View를 만들 경우 사용.
##   - template 파일의 경로만 지정.
# def home(request):
#     return render(request, "home.html")

polls/urls.py
from django.urls import path
from . import views   # polls/views.py 모듈 import
app_name = "polls"

# 요청 url - 실행할 view 
## path("url", view함수, name="이 설정이름")
urlpatterns = [
    path("welcome", views.welcome, name="welcome"),
    path("vote_list", views.list, name="list"),
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path('vote_create', views.vote_create, name="vote_create"),
    path('', views.list, name="polls_home"),  # http://127.0.0.1:8000/polls/
]
# http://127.0.0.1:8000/polls/list

# http://127.0.0.1:8000/polls/vote_form/3
# path parameter 변수 설정. <타입:변수이름>
## 타입: 문자열로 넘어온 값을 어떤 타입으로 변환할 지 지정.
## 변수이름: view의 어떤 파라미터에 값을 넘길지 view함수 파라미터이름

templates/home.html
<!-- root/templates/home.html -->
{% extends "layout.html" %}
{% load static %}

{% block title %}홈{% endblock title %}

{% block contents%}
<h2>설문 앱입니다.</h2>
목록 페이지에 다양한 설문 문항이 있습니다.
<p>
<img src="/static/imgs/survey.png"><br>
<img src="{% static 'imgs/survey.png' %}">

{% endblock contents%}

templates/layout.html
<!-- root/templates/layout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}설문앱{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
<!-- 
    메뉴 
    로그인 하지 않아야 나오는 메뉴: 가입, 로그인
    로그인 해야만 나오는 메뉴: 로그아웃, 설문등록, (회원정보수정, 회원정보조회)
    로그인 여부와 관계없는 메뉴: 설문 목록, (개별 설문 조회, 설문하기)
-->
{# {user.username}}, {{user.name}}, {{user.email} #}
<nav class="navbar navbar-expand-sm bg-success bg-opacity-10 mt-3">
    <div class="container">
        <div class="navbar-nav">
            <a href="{% url 'polls:list' %}" class="nav-link">설문목록</a>
            {% if user.is_authenticated %}
                <a href="{% url 'polls:vote_create' %}" class="nav-link">설문등록</a>
                <a href="{% url 'account:logout' %}" class="nav-link">로그아웃</a>
                <a href="{% url 'account:detail' %}" class="nav-link">
                    {# 로그인한 사용자의 username - 정보조회 #}
                    {{user.username}}
                </a>
            {% endif %}

            {% if not user.is_authenticated %}
                <a href="{% url 'account:create' %}" class="nav-link">가입</a>
                <a href="{% url 'account:login' %}" class="nav-link">로그인</a>
            {% endif %}
        </div>
    </div>
</nav>
<div class="container mt-3">
{% block contents %}{% endblock %}
</div>
</body>
</html>